sudo: false

notifications:
  email: false

cache:
  directories:
    - node_modules

language: node_js
node_js:
  - 8

script:
  - yarn test:ci
  - yarn lint
  - yarn build

branches:
  only:
    - master
    - /^greenkeeper/.*$/
