notifications:
  email: false

cache:
  directories:
    - node_modules

language: node_js

jobs:
  include:
    - stage: test
      script: yarn test:ci
      script: yarn lint
      script: yarn build
    - stage: release
        node_js: lts/*
        deploy:
          provider: script
          skip_cleanup: true
          script:
            - npx semantic-release
