notifications:
  email: false

cache: npm

language: node_js
node_js: 10

script:
  - yarn test:ci
  - yarn lint
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
