notifications:
  email: false

cache: yarn

language: node_js
node_js:
  - '12'

script:
  - yarn test:ci
  - yarn lint
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
