name: Build Status

on:
  push:
    branches:
      - master

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Manual deploy
        uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
