name: Pr Checker

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Manual deploy
        uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Manual deploy
        uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test:ci
